import React from 'react';

const CustomLink = () => {
    return (
        <div>
            <h1>Pending</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi mollitia iure est rem fuga obcaecati quis, eligendi accusantium unde esse nisi beatae veniam eos doloremque magni natus, sit quam similique dolor velit. Maiores quisquam, qui necessitatibus sed distinctio laboriosam in nihil ratione voluptatum suscipit ea, ullam ipsa fugit, earum expedita facere quas dignissimos hic. Aliquam quo recusandae facere repellat deserunt sapiente iste ad eaque qui doloremque necessitatibus nihil harum minus corrupti quae beatae libero autem animi excepturi, nam labore. Dolorem et voluptatum consequuntur cumque! Ratione nam nostrum odit magnam error incidunt dolore modi. Iste at quos nihil corporis eligendi, hic praesentium velit sit deleniti quae molestias fugit quibusdam. Praesentium amet delectus obcaecati maxime dolorem assumenda in dicta, esse modi consequatur ad nisi vero reiciendis laborum quos atque eum, animi placeat dolorum ipsam cumque adipisci! Perspiciatis esse sapiente consequuntur, vero quae delectus eaque quasi consectetur eveniet voluptatum possimus dolores illo obcaecati illum architecto dolorem repellendus velit et itaque pariatur. Suscipit dolorem cum soluta sed facilis perspiciatis obcaecati asperiores deserunt vero reiciendis, architecto dolore sit quo et ducimus consequuntur. Doloribus accusamus ut, vel perspiciatis necessitatibus voluptas quisquam est, vero explicabo dolor atque sequi qui maxime expedita fuga possimus ducimus cupiditate neque maiores tempore molestias, aliquam in nihil sed. Amet, perferendis! Sint velit, modi dolores, hic illum quas aliquid molestiae rerum accusamus delectus nihil numquam dolore voluptatem repellat vero quam dolor nisi illo optio cupiditate libero. Commodi minus quae magni laboriosam eaque sequi quam, nihil consectetur fugit odit incidunt esse, repudiandae iure distinctio eveniet nulla suscipit quia adipisci cum, soluta maxime voluptate recusandae. Quod nihil autem ut corporis beatae id neque quibusdam cumque sint itaque nam dolores nulla assumenda aliquam facilis, architecto eos enim odio omnis expedita officia in consequuntur. Adipisci, hic! Soluta, iusto. Aut id sunt dolorum sed deserunt mollitia? Natus temporibus asperiores architecto dolorem impedit, maiores veritatis nemo ipsum optio sed, perferendis animi voluptas cupiditate ad culpa inventore voluptatibus, sit doloremque eius. Accusamus ducimus laborum nulla sit itaque! Odit tempora id similique perferendis dignissimos ad, facere placeat aut ipsum? Recusandae et maiores doloribus ipsum nam amet, excepturi, nulla neque totam sed fugit omnis magni dicta vel nobis? Architecto voluptatibus, maxime incidunt natus, et ullam repellendus minima soluta, illo expedita tempore perspiciatis? Officia quo, expedita dolores labore repellat saepe dolor necessitatibus voluptate doloribus, unde ratione culpa similique itaque nulla eveniet, officiis odio dicta totam temporibus vel perspiciatis et. Soluta maxime debitis consectetur!</p>
        </div>
    );
};

export default CustomLink;